pipeline {
    agent {
        docker {
            image 'maven:3-jdk-8' 
            args '-v /root/.m2:/root/.m2 --network=devonpresentation_devondemonet'
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('sonar1') {
                  // requires SonarQube Scanner for Maven 3.2+
                  sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
                }
            }
        }
        stage('Deploy') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
            steps {
                sh 'docker build -t "petclinic:latest" -f DeployDockerfile'
            }
        }        
    }
}
 